# Generated by Django 4.2.5 on 2023-09-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_emailcampaign_schedule_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['organizer'], name='campaigns_c_organiz_dab149_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['manager'], name='campaigns_c_manager_3f2881_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['campaign'], name='campaigns_e_campaig_67ce13_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['published_date'], name='campaigns_e_publish_bd4ed4_idx'),
        ),
    ]
