# Generated by Django 4.2.5 on 2023-09-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
    ]
