# Generated by Django 4.2.5 on 2023-09-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscriber_last_name_alter_subscriber_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
